server:
    port: 9000

spring:
  application:
    name: gateway-service
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  eureka:
    enabled: false
  eager-load:
    enabled: true

zuul:
  host:
    connect-timeout-millis: 300000
    socket-timeout-millis: 300000
  prefix: /api
  routes:
    oauth-service:
      sensitiveHeaders:
      path: /oauth-service/**
      url: http://localhost:9001
    secured-service:
      sensitiveHeaders:
      path: /secured-service/**
      url: http://localhost:9002